name: Deploy Flutter Web to GitHub Pages

on:
  push:
    tags:
      - "v*.*.*" # Triggers only on new tags like v1.0.0

permissions:
  contents: write # Needed for gh-pages push

jobs:
  build-and-deploy:
    name: Build & Deploy Flutter Web
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: stable

      # 3️⃣ Enable web support
      - name: Enable web
        run: flutter config --enable-web

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5️⃣ Build web app
      - name: Build Flutter Web
        run: flutter build web --release --base-href /quick-attendance-app/

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          allow_empty_commit: false
